spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true