spring:
  application:
    name: customer-service
  profiles:
    active: dev

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# This property is not commonly used in newer Spring Cloud versions.
# Eureka discovery is enabled by default when the Eureka client dependency is present.
# You can omit this unless you?re working with a specific setup that requires it.
# spring:
#   cloud:
#     netflix:
#       eureka:
#         discovery:
#           enabled=true


